mapi_order_submit_pay_request:
    pattern:  /order/{id}/submit_pay_request
    defaults: { _controller: TopxiaMobileBundleV2:MobileOrder:submitPayRequest }
    methods: [GET, POST]

mapi_mobile_teacher_app:
    pattern:  /teacherApp
    defaults: { _controller: TopxiaMobileBundleV2:TeacherApp:index }

mapi_mobile_group_app:
    pattern:  /groupApp
    defaults: { _controller: TopxiaMobileBundleV2:GroupApp:index }

mapi_mobile_article_app:
    pattern:  /articleApp
    defaults: { _controller: TopxiaMobileBundleV2:ArticleApp:index }

mapi_mobile_article_app_list:
    path:     /articleApp/list
    defaults: { _controller: TopxiaMobileBundleV2:ArticleApp:list }
    methods: [GET, POST]

mapi_mobile_article_app_category:
    path:     /articleApp/category
    defaults: { _controller: TopxiaMobileBundleV2:ArticleApp:category }
    methods: [GET, POST]

mapi_mobile_article_detail_list:
    path:     /articleApp/detail/{id}
    defaults: { _controller: TopxiaMobileBundleV2:ArticleApp:detail }

topxia_mobile_alipay_notify:
    pattern:  /pay/{name}/alipay_notify
    defaults: { _controller: TopxiaMobileBundleV2:MobileAlipay:payNotify }

topxia_mobile_alipay_pay:
    pattern:  /alipay_pay
    defaults: { _controller: TopxiaMobileBundleV2:MobileAlipay:pay }

topxia_mobile_alipay_callback:
    pattern:  /pay/{name}/alipay_callback
    defaults: { _controller: TopxiaMobileBundleV2:MobileAlipay:payCallBack }

mapi_mobile_api:
    pattern:  /{service}/{method}
    defaults: { _controller: TopxiaMobileBundleV2:MobileApi:index }
    methods: [GET, POST]
